services:
  - type: web
    name: portfolio-cms-api
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./src/PortfolioCms.Api/Dockerfile
    dockerContext: .
    healthCheckPath: /health
    autoDeployTrigger: commit
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-cms-db
          property: connectionString
      - key: Jwt__Issuer
        value: portfolio-cms
      - key: Jwt__Audience
        value: portfolio-admin
      - key: Jwt__Secret
        generateValue: true
      - key: Jwt__ExpireMinutes
        value: 720
      - key: SeedAdmin__Username
        value: admin
      - key: SeedAdmin__Password
        sync: false
      - key: AllowedOrigins__0
        value: https://haihttt974.github.io
      - key: Database__AutoMigrate
        value: true
      - key: Cloudinary__CloudName
        sync: false
      - key: Cloudinary__ApiKey
        sync: false
      - key: Cloudinary__ApiSecret
        sync: false
      - key: Cloudinary__Folder
        value: portfolio-blog

databases:
  - name: portfolio-cms-db
    plan: free
    region: singapore
    databaseName: portfolio_cms
    user: portfolio_cms
