<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>98873d25-5d8d-48c5-a6a5-13d39f760dc4</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.17" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.17" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.17" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.17" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.17" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PortfolioCms.Common\PortfolioCms.Common.csproj" />
    <ProjectReference Include="..\PortfolioCms.Data\PortfolioCms.Data.csproj" />
    <ProjectReference Include="..\PortfolioCms.Service\PortfolioCms.Service.csproj" />
  </ItemGroup>

</Project>
